name: WAR Builds and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  duplicate_check:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master

  build:
    name: Build ${{ matrix.artifactTemplates.name }}
    needs: duplicate_check
    if: ${{ needs.duplicate_check.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        artifactTemplates:
          - name: DockerEngine-Interface
            path: artifacttemplates/http%3A%2F%2Fopentosca.org%2Fartifacttemplates/DockerEngine_DockerEngine-Interface-w1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build ${{ matrix.artifactTemplates.name }}
        run: | 
          cd $GITHUB_WORKSPACE/${{ matrix.artifactTemplates.path }}/source
          mvn -B package
      - name: Upload binary of artifact ${{ matrix.artifactTemplates.name }}
        uses: actions/upload-artifact@v2
        if: |
          github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags') || github.ref == 'refs/pull/18/merge'
        with:
          name: implementation_artifacts-WAR
          path: $GITHUB_WORKSPACE/*/${{ matrix.artifactTemplates.path }}/source/target/*.war
