name: WAR Builds and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  duplicate_check:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master

  build:
    name: Build ${{ matrix.artifactTempaltes.name }}
    needs: duplicate_check
    if: ${{ needs.duplicate_check.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        artifactTempaltes:
          - name: DockerEngine-Interface
            path: artifacttemplates/http%3A%2F%2Fopentosca.org%2Fartifacttemplates/DockerEngine_DockerEngine-Interface-w1
            sourceDir: source
            outputName: org_opentosca_artifactTemplates_DockerEngine__InterfaceDockerEngine
            runsOn: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build ${{ matrix.artifactTempaltes.name }}
        run: | 
          cd $GITHUB_WORKSPACE/${{ matrix.artifactTempaltes.path }}/${{ matrix.artifactTempaltes.sourceDir }}
          mvn -B package
